## Scikit-Learn Introduction

#To be cover in this NoteBook
0. An end-to-end scikit workflow
1. Getting data ready
2. Choose estimator/algorithm
3. Fit the model. 
4. Evaluate 
5. Save and load a trained model 
7.Putting it all together

## 0. End to end Scikit-Learn workflow

In [48]:
# Get the data ready
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplolib inline 
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

UsageError: Line magic function `%matplolib` not found.


In [11]:
# Feature Matrix 
X = heart_disease.drop("target", axis=1)

y = heart_disease["target"]

In [12]:
#pip install -U scikit-learn

In [13]:
# 2. Choose model and hyperparameters 

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# We will keep the default parameters 
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [23]:
# 3. Fit the model to training data

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size = 0.2)

In [24]:
clf.fit(X_train, y_train);

In [25]:
# Make a prediction 

y_preds = clf.predict(X_test)

In [26]:
y_preds

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int64)

In [27]:
y_test

123    1
144    1
97     1
286    0
115    1
      ..
233    0
56     1
268    0
146    1
216    0
Name: target, Length: 61, dtype: int64

In [30]:
# 4. Ealuate the model on training data and test data
clf.score(X_train, y_train)

1.0

In [31]:
clf.score(X_test, y_test)

0.8852459016393442

In [33]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.84      0.93      0.89        29
           1       0.93      0.84      0.89        32

    accuracy                           0.89        61
   macro avg       0.89      0.89      0.89        61
weighted avg       0.89      0.89      0.89        61



In [34]:
confusion_matrix(y_test, y_preds)

array([[27,  2],
       [ 5, 27]], dtype=int64)

In [35]:
accuracy_score(y_test, y_preds)

0.8852459016393442

In [41]:
# 5. Improve a model # Try different amunt of n_estimators

np.random.seed(0)

for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {clf.score(X_test, y_test)*100}\n")

Trying model with 10 estimators...
Model accuracy on test set: 83.60655737704919

Trying model with 20 estimators...
Model accuracy on test set: 88.52459016393442

Trying model with 30 estimators...
Model accuracy on test set: 83.60655737704919

Trying model with 40 estimators...
Model accuracy on test set: 88.52459016393442

Trying model with 50 estimators...
Model accuracy on test set: 91.80327868852459

Trying model with 60 estimators...
Model accuracy on test set: 86.88524590163934

Trying model with 70 estimators...
Model accuracy on test set: 85.24590163934425

Trying model with 80 estimators...
Model accuracy on test set: 88.52459016393442

Trying model with 90 estimators...
Model accuracy on test set: 86.88524590163934



In [43]:
# 6. Save a model and save it. 

import pickle

pickle.dump(clf, open("random_forest_model_1.pkl","wb"))

In [44]:
loaded_model  = pickle.load(open("random_forest_model_1.pkl", "rb"))

In [47]:
loaded_model.score(X_test, y_test)

0.8688524590163934

## 1. getting data to be ready to be used with machine learning 

1. Split in x & y
2. Proecess missing value 
3. converting non-numerical to numerical = feature encoding. 


In [49]:
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [50]:
X = heart_disease.drop("target", axis = 1)
y = heart_disease["target"]

In [55]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [54]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [56]:
# Split data into training and test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

In [57]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [58]:
X.shape

(303, 13)

## 1.1 Make sure its all numerical 

In [64]:
car_sales = pd.read_csv("car-sales-extended.csv")

In [65]:
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [63]:
len(car_sale)

1000

In [67]:
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

# Split data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
#Expected error

In [69]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'Honda'

In [70]:
# Turn categories into number
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_feature = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_feature)],
                               remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [71]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [73]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [77]:
# Refit the model 
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)

model.fit(X_train, y_train)

RandomForestRegressor()

In [78]:
model.score(X_test, y_test)


0.3235867221569877